#!/usr/bin/env python3
"""scan_assets.py -- scan the asset folders and (re)generate data/manifest.js.

The GM Console is a static, offline app: a browser cannot list a folder, so the
scene builder's pick lists come from a generated manifest. This script is the
one place the scan logic lives; both the command line (via sync-assets.sh) and
the local helper server (scripts/serve.py) call it.

It only ever reads the asset folders in this repo and writes data/manifest.js.
Standard library only, offline.
"""
from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ASSETS = os.path.join(ROOT, "assets")

# Backgrounds may be any image; character cutouts want transparency.
IMAGE_EXTS = (".jpg", ".jpeg", ".png", ".webp", ".gif")
CHARACTER_EXTS = (".png", ".webp")
AUDIO_EXTS = (".mp3", ".ogg", ".wav", ".m4a", ".webm")


def _humanize(stem: str) -> str:
    """A clean display label from a filename stem (no double hyphens)."""
    words = stem.replace("_", " ").replace("-", " ").split()
    return " ".join(w[:1].upper() + w[1:] for w in words) if words else stem


def _list(folder: str, exts, *, skip_hidden: bool):
    out = []
    directory = os.path.join(ASSETS, folder)
    if not os.path.isdir(directory):
        return out
    for name in os.listdir(directory):
        if not os.path.isfile(os.path.join(directory, name)):
            continue
        stem, ext = os.path.splitext(name)
        if ext.lower() not in exts:
            continue
        # A *_hidden file is a GM-only reveal variant, never a standalone pick.
        if skip_hidden and stem.endswith("_hidden"):
            continue
        out.append({"id": stem, "name": _humanize(stem), "src": f"assets/{folder}/{name}"})
    return out


def scan():
    """Return the asset lists (backgrounds, characters, audio) sorted for stable diffs."""
    backgrounds = (
        _list("maps", IMAGE_EXTS, skip_hidden=True)
        + _list("backgrounds", IMAGE_EXTS, skip_hidden=True)
    )
    backgrounds.sort(key=lambda e: e["src"])
    characters = _list("characters", CHARACTER_EXTS, skip_hidden=False)
    characters.sort(key=lambda e: e["src"])

    def audio(sub):
        items = _list(f"audio/{sub}", AUDIO_EXTS, skip_hidden=False)
        items.sort(key=lambda e: e["src"])
        return items

    return {
        "backgrounds": backgrounds,
        "characters": characters,
        "music": audio("music"),
        "ambience": audio("ambience"),
        "sfx": audio("sfx"),
    }


def _emit(entries) -> str:
    rows = [
        "  {{ id: {0}, name: {1}, src: {2} }}".format(
            json.dumps(e["id"]), json.dumps(e["name"]), json.dumps(e["src"])
        )
        for e in entries
    ]
    return ",\n".join(rows)


def write_manifest():
    data = scan()
    body = (
        "// ============================================================\n"
        "//  manifest.js  --  AUTO-GENERATED by scripts/scan_assets.py\n"
        "//  Do not edit by hand. Run scripts/sync-assets.sh or click\n"
        '//  "Rescan assets" in the GM window to regenerate it.\n'
        "//\n"
        "//  The scene builder reads these. BACKGROUNDS come from\n"
        "//  assets/maps and assets/backgrounds (files ending in _hidden are\n"
        "//  GM-only and excluded). CHARACTERS come from assets/characters.\n"
        "//  MUSIC / AMBIENCE / SFX come from assets/audio/{music,ambience,sfx}.\n"
        "// ============================================================\n\n"
        "export const BACKGROUNDS = [\n"
        + _emit(data["backgrounds"])
        + ("\n" if data["backgrounds"] else "")
        + "];\n\n"
        "export const CHARACTERS = [\n"
        + _emit(data["characters"])
        + ("\n" if data["characters"] else "")
        + "];\n\n"
        "export const MUSIC = [\n"
        + _emit(data["music"])
        + ("\n" if data["music"] else "")
        + "];\n\n"
        "export const AMBIENCE = [\n"
        + _emit(data["ambience"])
        + ("\n" if data["ambience"] else "")
        + "];\n\n"
        "export const SFX = [\n"
        + _emit(data["sfx"])
        + ("\n" if data["sfx"] else "")
        + "];\n"
    )
    out_path = os.path.join(ROOT, "data", "manifest.js")
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write(body)
    return data


if __name__ == "__main__":
    result = write_manifest()
    print(
        "Wrote data/manifest.js: {0} backgrounds, {1} characters, "
        "{2} music, {3} ambience, {4} sfx".format(
            len(result["backgrounds"]), len(result["characters"]),
            len(result["music"]), len(result["ambience"]), len(result["sfx"])
        )
    )
